### ISSUE TITLE
Feature Request: Multiple files

### ISSUE THREAD

**Issue by Mythical-Github** [Mateos81/KFTempArchiveExtractor#1]
The ability to to drag a folder containing multiple archives and have it export them without pause in between items would be very nice

**Comment by Mythical-Github** [comment]
Closed, did it myself, since I got no response at all here

**Comment by Mateos81** [comment]
Sorry; it was probably a matter of removing a few lines of code

**Comment by Mythical-Github** [comment]
No worries at all, was just going through old github stuff lol
